services:
  - type: web
    name: roznamcha
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn agri_business.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true