services:
  - type: web
    name: roznamcha-web
    runtime: python
    region: singapore
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn agri_business.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.12"